Repository Move-HandsOn/move-frontend, pull requests merged in 2024-11, with the labels that each got.

#17 refactor/tabBar
  src/components/tabBar/tabBar.module.css
  src/components/tabBar/tabBar.tsx
Labels: enhancement

#19 Fix/new activity
  src/components/HourInput/HourInput.module.css
  src/components/HourInput/HourInput.tsx
  src/components/NavBar/NavBar.module.css
  src/components/UploadAll/UploadAll.tsx
  src/pages/NewActivity/NewActivity.tsx
  src/pages/NewActivity/newActivity.module.css
Labels: fix/style

#25 Refactor/Adicionado melhorias no Autenticacao da rota autenticada
  src/routes/RequireAuth.tsx
Labels: bug
